question_data = [
    {"question": "Please give me a self-introduction.",
     "correct_answer": "blablabla"},
    {"question": "When you face some difficult, what can you do?",
     "correct_answer": "blablabla"},
    {"question": "If you are in a new data science team, how to work with cross-functional departments? "
                 "Do you have experience working with internal and external clients?",
     "correct_answer": "blablabla"},
    {"question": "What do you know about our company?",
     "correct_answer": "blablabla"},
    {"question": "What is your future plan in our company?",
     "correct_answer": "blablabla"},
    {"question": "How do you prioritize your workflow?",
     "correct_answer": "blablabla"},
    {"question": "What make your down in your work?",
     "correct_answer": "blablabla"},
    {"question": "How do you clean and process your data? ",
     "correct_answer": "blablabla"},
    {"question": "Do you have Big Data dealing experience, What size of the data you used to work with?",
     "correct_answer": "blablabla"},
    {"question": "How would you deal with categorical features of low cardinality? Of high cardinality? "
                 "how to deal with zipcode, encoding？",
     "correct_answer": "blablabla"},
    {"question": "How did you do the model deployment?",
     "correct_answer": "blablabla"},
    {"question": "How to deal with the missing values in Time Series ML problem?",
     "correct_answer": "blablabla"},
    {"question": "How to explain Random in Random Forest?",
     "correct_answer": "blablabla"},
    {"question": "What is bagging??",
     "correct_answer": "blablabla"},
    {"question": "What is boosting?",
     "correct_answer": "blablabla"},
    {"question": "Which package did you use in your NLP? Please give one example.",
     "correct_answer": "blablabla"},
    {"question": "What are the differences between snowflake and Databricks?",
     "correct_answer": "blablabla"},
    {"question": "Can you tell us about any skills or experience you have that might be helpful in this job?",
     "correct_answer": "blablabla"},
    {"question": "What motivates you to do a great job at work, other than the paycheck?",
     "correct_answer": "blablabla"},
    {"question": "Tell us about a time when you found it difficult to work with someone. "
                 "How did you handle the situation?",
     "correct_answer": "blablabla"},
    {"question": "Please tell us what interests you most about this job "
                 "(HP Sr Business Data Analyst at Point32Health)? "
                 "Why is this something that you want to focus your efforts and attention on?",
     "correct_answer": "blablabla"},
    {"question": "Besides your experiences, what attributes and qualities do you possess "
                 "that you believe are critical to success in this role?",
     "correct_answer": "blablabla"},
    {"question": "What professional or personal experiences do you bring to this role that will make you successful?",
     "correct_answer": "blablabla"},
    {"question": "Tell me about a time when you tackled something you had never done before.",
     "correct_answer": "blablabla"},
    {"question": "Describe a time when you had to juggle multiple projects or customers at the same time. "
                 "How did you organize your time? What was the result?",
     "correct_answer": "blablabla"},
    {"question": "Tell me about a time when you were communicating with someone and there was a misunderstanding. "
                 "How did you get things back on track?",
     "correct_answer": "blablabla"},
    {"question": "Tell me about a time you set a goal for yourself. "
                 "How did you go about ensuring that you would meet your objective?",
     "correct_answer": "blablabla"},
    {"question": "Describe a time when your team or company was undergoing change. "
                 "How did that impact you, and how did you adapt?",
     "correct_answer": "blablabla"},
    {"question": "Why are you interested in our company?",
     "correct_answer": "blablabla"},
    {"question": "What model did you use in your project?",
     "correct_answer": "blablabla"},
    {"question": "Why do you choose that model?",
     "correct_answer": "blablabla"},
    {"question": "How do you present your work to non-technical people?",
     "correct_answer": "blablabla"},
    {"question": "What is your experience using python or R?",
     "correct_answer": "blablabla"},
    {"question": "Have you ever used SQL?",
     "correct_answer": "blablabla"},
    {"question": "Have you ever used deep learning?",
     "correct_answer": "blablabla"},
    {"question": "Have you ever used Spark?",
     "correct_answer": "blablabla"},
    {"question": "Which visualization tool have you used?",
     "correct_answer": "blablabla"},
    {"question": "What is your metrics when you evaluate your ML model? "
                 "Can you give an example of one your favorite ML model to Non-technical Stakeholders?",
     "correct_answer": "blablabla"},
    {"question": "What are the assumption of linear regression?",
     "correct_answer": "blablabla"},
    {"question": "Can you tell us about a time when you had to work on a project with unclear or constantly "
                 "changing requirements? How did you adapt?",
     "correct_answer": "blablabla"},
    {"question": "What are the feature selection methods used to select the right variables? "
                 "Please give me some examples",
     "correct_answer": "blablabla"},
    {"question": "Mention three ways to make your model robust to outliers?",
     "correct_answer": "blablabla"},
    {"question": "What are L1 and L2 regularization? What are the differences between the two?",
     "correct_answer": "blablabla"},
    {"question": "What are the evaluation metrics that can be used for multi-label classification?",
     "correct_answer": "blablabla"},
    {"question": "What is the ROC curve and when should you use it?",
     "correct_answer": "blablabla"},
    {"question": "What is missing data? Different types of missing data? Cause of them? "
                 "Methods to find them?  How to deal with them ?",
     "correct_answer": "blablabla"},
    {"question": "The job description frequently mentioned AWS cloud, "
                 "such as S3, EC2, Lambda, SageMaker. How to answer? ",
     "correct_answer": "blablabla"},
    {"question": "What are the assumptions made by the ARIMA model?",
     "correct_answer": "blablabla"},
    {"question": "What is SHAP and how does it work?",
     "correct_answer": "blablabla"},
    {"question": "Tell me the advantages and disadvantages of SMOTE.",
     "correct_answer": "blablabla"},
    {"question": "Explain metrics for linear regression model? which one is more sensitive to outliers?",
     "correct_answer": "blablabla"},
    {"question": "How do you find and deal with outliers?",
     "correct_answer": "blablabla"},
    {"question": "Do you have any questions for me?",
     "correct_answer": "blablabla"},
    {"question": "Do you have any questions for me?",
     "correct_answer": "blablabla"},
]
